# Site settings
title: CS231n Convolutional Neural Networks for Visual Recognition
email: damminhtienchl@gmail.com
description: "Course materials and notes for Stanford class CS231n: Convolutional Neural Networks for Visual Recognition."
baseurl: "cs231n-vietnamese"
url: "https://damminhtien.github.io/cs231n-vietnamese"
twitter_username: cs231n
github_username:  cs231n

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

